name: appliedai_daftpgmdemo
dependencies:
- python=3.5
- jupyter>=1.0.0
- ipywidgets
- numpy=1.11.1
- scipy=0.18.0
- matplotlib=1.5.1
- pandas=0.18.1
- pip>=8.1.2
- pip:
    - daft==0.0.4
    - watermark=1.1.3
